-- Admin Portal — admin_credentials table + default account
-- Run: docker exec -i boli-postgres-1 psql -U boli -d boli < infrastructure/postgres/seed_admin_portal.sql

CREATE TABLE IF NOT EXISTS admin_credentials (
  admin_id      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  email         VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name     VARCHAR(100) NOT NULL,
  role          VARCHAR(50)  NOT NULL DEFAULT 'ADMIN',
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMP WITH TIME ZONE,
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Default credentials: admin@boli.pk / Admin@Boli2024
-- bcrypt hash cost 12, generated by Go bcrypt.GenerateFromPassword
INSERT INTO admin_credentials (email, password_hash, full_name, role)
VALUES (
  'admin@boli.pk',
  '$2a$12$aJU7QH3Ne3T3e1p1z4v1z.251wx.41DP125zro89dmP8RwLb4ZLRi',
  'System Administrator',
  'SUPER_ADMIN'
) ON CONFLICT (email) DO NOTHING;
